<?xml version="1.0" encoding="utf-8"?><Database Name="QL_HOITHAO" Class="QuanLyHoiThaoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-S56F490\DUONGTHUANQUANG;Initial Catalog=QL_HOITHAO;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_HOITHAOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Authors" Member="Authors">
    <Type Name="Author">
      <Column Name="author_id" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="affiliation" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Author_Paper" Member="Papers" ThisKey="author_id" OtherKey="author_id" Type="Paper" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="user_id" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="salt" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="affiliation" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Review" Member="Reviews" ThisKey="user_id" OtherKey="reviewer_id" Type="Review" />
    </Type>
  </Table>
  <Table Name="dbo.Paper" Member="Papers">
    <Type Name="Paper">
      <Column Name="paper_id" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="abstract" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="author_id" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Paper_Review" Member="Reviews" ThisKey="paper_id" OtherKey="paper_id" Type="Review" />
      <Association Name="Author_Paper" Member="Author" ThisKey="author_id" OtherKey="author_id" Type="Author" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Review" Member="Reviews">
    <Type Name="Review">
      <Column Name="review_id" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="paper_id" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="reviewer_id" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="rating" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="review_confident" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comments" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Paper_Review" Member="Paper" ThisKey="paper_id" OtherKey="paper_id" Type="Paper" IsForeignKey="true" />
      <Association Name="User_Review" Member="User" ThisKey="reviewer_id" OtherKey="user_id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>